myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('', include('shop.urls',namespace='shop')),
]


urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.FORCE_STATIC_FILE_SERVING and not settings.DEBUG:
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    settings.DEBUG = False


admin.site.site_header = "Anika Medicine Shop Admin"
admin.site.site_title = "Anika Medicine Shop Admin Portal"
admin.site.index_title = "Anika Medicine Shop Researcher Portal"

shop/urls.py
from django.urls import path
from . import views
from django.urls import reverse_lazy

app_name = 'shop'

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('ajax/search-and-filter/', views.load_search_and_filter, name="ajax_load_search_and_filter"),
    path('update_item/', views.UpdateItemView.as_view(), name="update_item"),
    path('confirm-order/', views.confirm_order, name="confirm_order"),
    path('report-generate/', views.report_generate, name="report_generate"),
    
]

shop/models.py
from django.db import models
from base.models import MEDICINE_TYPE
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.
class Generic(models.Model):
    name  = models.CharField(max_length=150)
    def __str__(self):
        return self.name

class Brand(models.Model):
    name  = models.CharField(max_length=150)
    def __str__(self):
        return self.name

class Place(models.Model):
    name  = models.CharField(max_length=150)
    def __str__(self):
        return self.name

class Medicine(models.Model):
    name  = models.CharField(max_length=150)
    buy_price = models.FloatField()
    sell_price = models.FloatField()
    generic = models.ForeignKey(Generic, on_delete=models.CASCADE)
    brand  = models.ForeignKey(Brand, on_delete=models.CASCADE)
    type =  models.CharField(max_length=15,choices=MEDICINE_TYPE)
    quantity = models.IntegerField()
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    complete_order = models.BooleanField()
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    class Meta:
            verbose_name = 'Orders'
            verbose_name_plural = '1. Orders'

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        items = self.orderitem_set.all()
        return sum(i.get_total for i in items)

    @property
    def get_profit_total(self):
        items = self.orderitem_set.all()
        return sum(i.get_total_profit for i in items)


class OrderItem(models.Model):
    product = models.ForeignKey(Medicine, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0, null=True, blank=True)

    class Meta:
            verbose_name = 'OrderItems'
            verbose_name_plural = '2. OrderItems'

    def __str__(self):
        return str(self.order)
    
    @property
    def get_total(self):
        return self.product.sell_price  * self.quantity
    
    @property
    def get_total_profit(self):
        return (self.product.sell_price - self.product.buy_price)  * self.quantity

shop/views.py
from ast import Or
from multiprocessing import context
from django.shortcuts import render, get_object_or_404 , HttpResponse
from django.views import View 
from .models import Medicine, Brand , Generic ,Order, OrderItem
from django.contrib import messages
import json
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator

# Create your views here.

@method_decorator(login_required, name='dispatch')
class HomeView(View):
    def get(self, request):
        brands = Brand.objects.all()
        generics = Generic.objects.all()
        medicines = Medicine.objects.all()
        medicines_count = medicines.count()
        paginator = Paginator(medicines, 10) # Show 25 contacts per page.
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        try:
            order = get_object_or_404(Order, user=request.user,complete_order=False)
            items = order.orderitem_set.all() or None
        except:
            order = None
            items = None
        context = {
            'brands':brands,
            'generics':generics,
            'medicines':page_obj,
            'medicines_count':medicines_count,
            'order':order,
            'items':items

        }
        return render(request, "shop/home.html", context)
   

@method_decorator(login_required, name='dispatch')
class UpdateItemView(View):
    def post(self, request):
        print("-----------------------------")
        productId = request.POST.get('product_id')
        action = request.POST.get('action')
        print(productId, action)
        user = request.user
        product = Medicine.objects.get(id=productId)
        order, created = Order.objects.get_or_create(user=user,complete_order=False)
        orderitem, created = OrderItem.objects.get_or_create(order=order, product=product)
        
        if action == 'add':
            if product.quantity - orderitem.quantity > 0:
                orderitem.quantity = (orderitem.quantity +1)
            else:
                orderitem.quantity = (orderitem.quantity)
                messages.success(self.request, f'{orderitem.product}. Item Have Left {orderitem.quantity}.')
        elif action == 'sub':
            orderitem.quantity = (orderitem.quantity -1)
        orderitem.save()
        if action == 'del':
            orderitem.delete()
            messages.success(self.request, f'{orderitem.product}. Item deleted From Cart.')
        
        if orderitem.quantity <=0:
            orderitem.delete()

        order = get_object_or_404(Order, user=request.user,complete_order=False)
        items = order.orderitem_set.all()
        context = {
            'order':order,
            'items':items

        }
        return render(request, "partials/cart_result.html", context)
        # return JsonResponse('item' , safe=False)


def load_search_and_filter(request):
    brand_list = request.GET.getlist('brand_list[]')
    generic_list = request.GET.getlist('generic_list[]')
    search_value = request.GET.get('search_value')
    medicines = Medicine.objects.all()
    if brand_list and generic_list:
        medicines = Medicine.objects.filter(name__icontains=search_value, brand__name__in = brand_list, generic__name__in = generic_list)
    elif brand_list:
        medicines = Medicine.objects.filter(name__icontains=search_value, brand__name__in = brand_list)
    elif generic_list:
        medicines = Medicine.objects.filter(name__icontains=search_value, generic__name__in = generic_list)
    elif search_value:
        medicines = Medicine.objects.filter(name__icontains=search_value)
    medicines_count = medicines.count()
    paginator = Paginator(medicines, 10) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'partials/search.html', {'medicines':page_obj,'medicines_count':medicines_count})


def confirm_order(request):
    orderId = request.POST.get('order_id')
    print(orderId)
    order = Order.objects.get(id=orderId)
    order.complete_order = True
    order.save()
    items = order.orderitem_set.all()
    for i in items:
        print(i.product.id, i.quantity)
        medicine = Medicine.objects.get(id=i.product.id)
        medicine.quantity = medicine.quantity - i.quantity
        medicine.save()

    return HttpResponse("ok")


import datetime
def report_generate(request):
    from_date = request.GET.get("from_date")
    to_date = request.GET.get("to_date")
    if from_date and to_date:
        orders = Order.objects.filter(updated_at__range=[from_date,to_date], complete_order=True)
    else:
        orders = Order.objects.filter(updated_at=datetime.date.today(), complete_order=True)
    
    total_sell = 0
    total_profit = 0
    for i in orders:
        total_sell = total_sell + i.get_cart_total
        total_profit = total_profit + i.get_profit_total

    context = {
        'total_orders': orders.count(),
        'total_sell' : total_sell,
        'total_profit': total_profit,
        'from_date': from_date,
        'to_date' : to_date

    }
    return render(request, 'shop/report.html', context)

templates/shop/home.html
{% extends 'base.html' %}
{% load static %}
    {% block content %}
        <div class="row">
          <!-- BEGIN SEARCH RESULT -->
          <div class="col-md-12">
            <div class="grid search">
              <div class="grid-body">
                <div class="row">
                  <!-- BEGIN FILTERS -->
                  <div class="col-md-2">
                    <h2 class="grid-title"><i class="fa fa-filter"></i> Filters</h2>
                    <hr>
                    
                    <!-- BEGIN FILTER BY CATEGORY -->
                    <h4>By Brand:</h4>
                    {% for brand in brands %}
                    <div class="checkbox" id="brandfilterForm" data-brand-filter-url="{% url 'shop:ajax_load_search_and_filter' %}">
                      <label><input name="brand[]" type="checkbox" class="icheck" value="{{brand.name}}"> {{brand.name}}</label>
                    </div>
                    {% endfor %}
                    <!-- END FILTER BY CATEGORY -->
                    <!-- BEGIN FILTER BY CATEGORY -->
                    <h4>By Generic:</h4>
                    {% for generic in generics %}
                    <div class="checkbox">
                      <label><input name="generic[]" type="checkbox" class="icheck" value="{{generic.name}}"> {{generic.name}}</label>
                    </div>
                    {% endfor %}
                    <!-- END FILTER BY CATEGORY -->
                  </div>
                  <!-- END FILTERS -->
                  <!-- BEGIN RESULT -->
                  <div class="col-md-6">
                    <h2><i class="fa fa-medkit" aria-hidden="true"></i> Medicine</h2>
                    <hr>
                    <!-- BEGIN SEARCH INPUT -->
                    <div class="input-group" id="searchForm" data-search-url="{% url 'shop:ajax_load_search_and_filter' %}">
                        <input id="search" type="text" name="search" class="form-control">
                        <span class="input-group-btn">
                          <input class="btn btn-primary" type="submit" value="Search">
                        </span>
                    </div>

                  <div id="search_result">
                    <!-- END SEARCH INPUT -->
                    <p>Search Result : {{medicines_count}}</p>
                    
                    <div class="padding"></div>
                    
                    <!-- BEGIN TABLE RESULT -->
                    <div class="table-responsive">
                      <table class="table table-hover">
                        <thead>
                          <tr>
                            <th>Medicine Name</th>
                            <th class="rate text-center">Place</th>
                            <th class="rate text-center">Quantity</th>
                            <th class="rate text-center">Price</th>
                            <th class="rate text-center">Action</th>
            
                          </tr>
                        </thead>
                        <tbody>
                        {% for medicine in medicines %}
                        <tr>
                          <td class="product"><strong>{{medicine.name}}</strong> ({{medicine.type}})<br>{{medicine.generic}}</td>
                          <td class="rate text-center">{{medicine.place}}</td>
                          <td class="rate text-center">{{medicine.quantity}}</td>
                          <td class="rate text-center">${{medicine.sell_price}}</td>
                          <td class="price text-center">
                            <a style="font-weight: bold;" id="updateCart" name="cart[]" data-update-cart-url="{% url 'shop:update_item' %}" class="ml-4" data-product={{medicine.id}} data-action="add"><i class="fa fa-cart-plus" aria-hidden="true"></i></a></td>                
                        </tr>
                        {% endfor %}

                      </tbody></table>
                    </div>
                    <!-- END TABLE RESULT -->
                    
                    <!-- BEGIN PAGINATION -->
                    {% include 'partials/pagination.html' %}
                    <!-- END PAGINATION -->
                  </div>
                </div>
                  <!-- END RESULT -->
                  <div id="cart_result">
                  <div class="col-md-4">
                    <h2><i class="fa fa-file-pdf-o" aria-hidden="true"></i> Invoice </h2>
                    <hr>
                    <table class="table table-cart table-mobile">
                      <thead>
                        <tr>
                          <th>Product</th>
                          <th>Price</th>
                          <th>Quantity</th>
                          <th>Total</th>
                          <th></th>
                        </tr>
                      </thead>
                     
                      <tbody>
                        {% for item in items %}
                        <tr>
                          <td class="product-col">
                            <div class="product">
                                <p>{{item.product.name}}</p>
                            </div><!-- End .product -->
                          </td>
                          <td class="price-col">{{item.product.sell_price}}</td>
                          <td class="quantity-col">
                              <div class="cart-product-quantity">
                              <a style="font-weight: bold;" class="mr-4" id="inupdateCart" name="incart[]" data-update-cart-url="{% url 'shop:update_item' %}" data-product = {{item.product.id}} data-action = "sub"><i class="fa fa-minus-circle" aria-hidden="true"></i></a>
                              &nbsp; {{item.quantity}}  &nbsp;
                              <a style="font-weight: bold;" class="ml-4" id="inupdateCart" name="incart[]" data-update-cart-url="{% url 'shop:update_item' %}" data-product = {{item.product.id}} data-action = "add"><i class="fa fa-plus-circle" aria-hidden="true"></i></a>
                              </div><!-- End .cart-product-quantity -->
                          </td>
                          <td class="total-col">{{item.get_total}}</td>
                          <td class="remove-col"><a id="inupdateCart" name="incart[]" data-update-cart-url="{% url 'shop:update_item' %}" data-product = {{item.product.id}} data-action = "del"><i class="fa fa-trash" aria-hidden="true"></i></a></td>
                        </tr>
                        {% endfor %}
                        
                      </tbody>
        
                      <tbody>
                        
                        <tr>
                          <td class="product-col">
                            <div class="product">
                                <p><b>Grand Total</b></p>
                            </div><!-- End .product -->
                          </td>
                          <td class="total-col"></td>
                          <td class="total-col"></td>
                          <td class="total-col">{{order.get_cart_total}}</td>
                        </tr>
                      </tbody>
                    </table><!-- End .table table-wishlist -->
                    {% if order %}
                    <input class="center-block btn btn-primary" type="button" id="bt" onclick="show_alert()" order-data={{order.id}} value="Invoice Print" />
                    {% else %}
                    <input class="center-block" type="button" value="Invoice Print" />
                    {% endif %}
                  </div>
                  
                  <div id="printableArea" class="col-md-4" style="visibility: hidden">
                    <h2 style="text-align: center;"> Anika Medicine Shop </h2>
                    <h3> Invoice No : {{order.id}} </h3>
                    <table class="table table-cart table-mobile">
                      <thead>
                        <tr>
                          <th>Product</th>
                          <th>Price</th>
                          <th>Quantity</th>
                          <th>Total</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for item in items %}
                        <tr>
                          <td class="product-col">
                            <div class="product">
                                <p>{{item.product.name}}</p>
                            </div><!-- End .product -->
                          </td>
                          <td class="price-col">{{item.product.sell_price}}</td>
                          <td class="quantity-col">{{item.quantity}}</td>
                          <td class="total-col">{{item.get_total}}</td>
                        </tr>
                        {% endfor %}
                      </tbody>
                      <tbody>
                        <tr>
                          <td class="product-col">
                            <div class="product">
                                <p>Grand Total</p>
                            </div><!-- End .product -->
                          </td>
                          <td class="total-col"></td>
                          <td class="total-col"></td>
                          <td class="total-col">{{order.get_cart_total}}</td>
                        </tr>
                      </tbody>
                    </table><!-- End .table table-wishlist -->
                  </div>


                </div>
                </div>
                </div>
              </div>
            </div>
          </div>
          <!-- END SEARCH RESULT -->
        
    {% include 'partials/css.html' %}
    {% include 'partials/js.html' %}

{% endblock content %}

templates/shop/report.html
{% extends 'base.html' %}
{% load static %}
    {% block content %}
    <form method="GET" action="{% url 'shop:report_generate' %}">
      <div class="row" style="margin-bottom:20px">
        <div class="col-xs-4 center-block" style="float:none">
          <div class="col-md-6">
            <label>From Date:</label>
            <input class="form-control" type="date"  name="from_date" value="{{from_date}}" required>
          </div>
          <div class="col-md-6">
            <label>To Date:</label>
            <input class="form-control" type="date" name="to_date" value="{{to_date}}" required>
          </div>
        </div>
        <input style="margin-top: 23px;" class="btn btn-primary" type="submit">
      </div>
    </form>

    <div class="row">
      <!-- BEGIN SEARCH RESULT -->
      <div class="col-md-12">
        <div class="grid search">
          <div class="grid-body">
            <div class="row">
                <div class="col-md-4">
                    <div class="card border-info mx-sm-1 p-3">
                        <div class="text-info text-center mt-3"><h4>Total Sell</h4></div>
                        <div class="text-info text-center mt-2"><h1>{{total_sell}}</h1></div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card border-success mx-sm-1 p-3">
                        <div class="text-success text-center mt-3"><h4>Total Profit</h4></div>
                        <div class="text-success text-center mt-2"><h1>{{total_profit}}</h1></div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card border-danger mx-sm-1 p-3">
                        <div class="text-danger text-center mt-3"><h4>Total Orders</h4></div>
                        <div class="text-danger text-center mt-2"><h1>{{total_orders}}</h1></div>
                    </div>
                </div>
             </div>
        </div>
      </div>
    </div>
  </div>      
    {% include 'partials/css.html' %}
<script>
    $('.input-group.date').datepicker({format: "dd.mm.yyyy"}); 
</script>

{% endblock content %}