accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = "accounts"

urlpatterns = [
    path('', views.home, name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    #token
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    
    path('change_password/', auth_views.PasswordChangeView.as_view(template_name='accounts/change_password.html' , success_url=reverse_lazy('accounts:password_change_done')), name='change_password'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),name='password_change_done'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html' , success_url=reverse_lazy('accounts:password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html' , success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('', include('shop.urls',namespace='shop')),
]


urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.FORCE_STATIC_FILE_SERVING and not settings.DEBUG:
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    settings.DEBUG = False


admin.site.site_header = "Anika Medicine Shop Admin"
admin.site.site_title = "Anika Medicine Shop Admin Portal"
admin.site.index_title = "Anika Medicine Shop Researcher Portal"

shop/urls.py
from django.urls import path
from . import views
from django.urls import reverse_lazy

app_name = 'shop'

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('ajax/search-and-filter/', views.load_search_and_filter, name="ajax_load_search_and_filter"),
    path('update_item/', views.UpdateItemView.as_view(), name="update_item"),
    path('confirm-order/', views.confirm_order, name="confirm_order"),
    path('report-generate/', views.report_generate, name="report_generate"),
    
]

base/models.py
from django.db import models

MEDICINE_TYPE =(
    ("capsule", "Capsule"),
    ("tablet", "Tablet"),
    ("syrup", "Syrup"),
    ("injection", "Injection")
)

templates/base.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <!DOCTYPE html>
    <head>
        <meta charset="utf-8">
        <title>Medicine Shop</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
        <link href="https://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://netdna.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    </head>
</head>

<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'shop:home' %}">Medicine Shop</a>
          </div>
      
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              {% if request.user.is_authenticated %}
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'shop:report_generate' %}">Report</a>
              </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:change_password' %}">Change Password</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" >( {{user}} )</a>
                </li>

              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
            </li>
              {% endif %}
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>                 
                       
    <!-- main content -->
    {% block content %}

    {% endblock content %}
    <!-- end of main content -->


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script src="{% static '/cart.js' %}"></script>
  </body>

</html>

templates/search.html
    <!-- END SEARCH INPUT -->
    <p>Search Result : {{medicines_count}}</p>
    
    <div class="padding"></div>
    
    <!-- BEGIN TABLE RESULT -->
    <div class="table-responsive">
      <table class="table table-hover">
        <tbody>
        {% for medicine in medicines %}
        <tr>
          <td class="product"><strong>{{medicine.name}}</strong> ({{medicine.type}})<br>{{medicine.generic}}</td>
          <td class="rate text-right">{{medicine.quantity}}</td>
          <td class="rate text-right">${{medicine.sell_price}}</td>
          <td class="price text-right">
            <a style="font-weight: bold;" href="" class="update-cart ml-4" data-user = {{user.id}} data-product = {{medicine.id}} data-action = "add"><i class="fa fa-cart-plus" aria-hidden="true"></i></a></td>                
          </tr>
        {% endfor %}

      </tbody></table>
    </div>
    <!-- END TABLE RESULT -->
    
    <!-- BEGIN PAGINATION -->
    {% include 'pagination.html' %}
    <!-- END PAGINATION -->
  </div>